services:
  pod:
    image: lazuardytech/pod
    container_name: pod
    restart: unless-stopped
    env_file: .env
    ports:
      - '20128:20128'
    volumes:
      - pod-data:/app/data
volumes:
  pod-data:
